FROM alpine:latest

RUN apk update && \
    apk add --no-cache nodejs npm curl nginx && \
    npm install -g npm@latest pnpm && \
    rm -rf /var/cache/apk/*

WORKDIR /app

COPY . .

COPY dockerfile/nginx.conf /etc/nginx/nginx.conf

RUN pnpm install --no-frozen-lockfile && \
    pnpm build

EXPOSE 8282 8283

CMD ["nginx", "-g", "daemon off;"]
